{
 "title": "DBA进程监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "select rshost from tb_monitor_host_info group by rshost;"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu_core",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,'_core' ),\nsum(CONVERT(cpu_info -> '$.total', UNSIGNED INTEGER) ) cpu_total\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "cpu_load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(cpu_info -> '$.load', UNSIGNED INTEGER) ) cpu_load\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "cpu_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(cpu_info -> '$.id', UNSIGNED INTEGER) ) cpu_id\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "CPU_wait",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(cpu_info -> '$.wa', UNSIGNED INTEGER) ) cpu_wait\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORY INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "mem_total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(mem_info -> '$.total', UNSIGNED INTEGER) ) mem_total\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "mem_used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(mem_info -> '$.used', UNSIGNED INTEGER) ) mem_used\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "mem_free",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(CONVERT(mem_info -> '$.free', UNSIGNED INTEGER) ) mem_free\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    }
   ]
  },
  { "title": "DISK INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "disk_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,\":\",part) part,\nsum(CONVERT(disk_info -> '$.total', UNSIGNED INTEGER) ) disk_total\nfrom tb_monitor_disk_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,\":\",part) part,\nsum(CONVERT(disk_info -> '$.used', UNSIGNED INTEGER) ) disk_used\nfrom tb_monitor_disk_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,\":\",part) part,\nsum(CONVERT(disk_info -> '$.free', UNSIGNED INTEGER) ) disk_free\nfrom tb_monitor_disk_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(json_unquote(io_info -> '$.Total.write')) disk_write\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(json_unquote(io_info -> '$.Total.read')) disk_read\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_avgqu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,\":\",dev) part,\nsum(avgqu) disk_avgqu\nfrom tb_monitor_disk_util_qu_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "disk_util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,\":\",dev) part,\nsum(util) disk_util\nfrom tb_monitor_disk_util_qu_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
    }
   ]
  },
  {
   "title": "NET INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "speed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nconcat(rshost,'_core' ),\nsum(CONVERT(net -> '$.speed', UNSIGNED INTEGER) ) net_total\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "net_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(json_unquote(net -> '$.Total')) net_Total\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "net_send",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(json_unquote(net -> '$.send')) net_send\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "net_receive",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "select UNIX_TIMESTAMP(a_time) AS \"time\",\nrshost,\nsum(json_unquote(net -> '$.receive')) net_receive\nfrom tb_monitor_host_info\nwhere rshost = '$host' and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    }
   ]
  },
  {
   "title": "PROCESS INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "进程CPU百分比",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(t1.a_time) AS \"time\",\n  concat(t1.rshost,':',t1.rsport,' ',t2.remarks) AS metric,\n  sum(t1.cpu) \nFROM tb_monitor_process_io_info t1 join tb_monitor_process_info t2 on t1.md5_str = t2.md5_str\nwhere t1.rshost = '$host' and t1.cpu > 20 and $__timeFilter(t1.a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(t1.a_time)"
      }
     ]
    },
    {
     "title": "进程内存使用情况",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "rawSql": "\n\nSELECT\n  UNIX_TIMESTAMP(t1.a_time) AS \"time\",\n  concat(t1.rshost,':',t1.rsport,' ',t2.remarks) AS metric,\n  sum(t1.mem) \nFROM tb_monitor_process_io_info t1 join tb_monitor_process_info t2 on t1.md5_str = t2.md5_str\nwhere t1.rshost = '$host' and t1.mem > 5 and $__timeFilter(t1.a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(t1.a_time)"
      }
     ]
    },
    {
     "title": "进程读取量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(t1.a_time) AS \"time\",\n  concat(t1.rshost,':',t1.rsport,' ',t2.remarks) AS metric,\n  sum(t1.io_r) \nFROM tb_monitor_process_io_info t1 join tb_monitor_process_info t2 on t1.md5_str = t2.md5_str\nwhere t1.rshost = '$host' and t1.io_r > 10240 and $__timeFilter(t1.a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(t1.a_time)"
      }
     ]
    },
    {
     "title": "进程写入量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(t1.a_time) AS \"time\",\n  concat(t1.rshost,':',t1.rsport,' ',t2.remarks) AS metric,\n  sum(t1.io_w) \nFROM tb_monitor_process_io_info t1 join tb_monitor_process_info t2 on t1.md5_str = t2.md5_str\nwhere t1.rshost = '$host' and t1.io_w > 10240 and $__timeFilter(t1.a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(t1.a_time)"
      }
     ]
    },
    {
     "title": "进程网络入口流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(a_time) AS \"time\",\n  concat(rsinfo,'_',remote) AS metric,\n  sum(in_info) \nFROM tb_monitor_port_net_info\nwhere rsinfo like '$host%' and in_info > 10240 and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    },
    {
     "title": "进程网络出口流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(a_time) AS \"time\",\n  concat(rsinfo,'_',remote) AS metric,\n  sum(out_info) \nFROM tb_monitor_port_net_info\nwhere rsinfo like '$host%' and out_info > 10240 and $__timeFilter(a_time)\nGROUP BY 1,2\nORDER BY UNIX_TIMESTAMP(a_time)"
      }
     ]
    }
   ]
  }
 ]
}